version: "3.0"
services:
  questdb:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "questdb"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      QUEST_URL: "http://localhost:9000"
      TABLE_NAME: "mytable"
      COLUMNS: "temperature, location"
      LABELS: "filterTemp, sensorLocation"
    ports:
      - 80:80
